### ISSUE TITLE
Storage and database size

### ISSUE THREAD

**Issue by computron** [hackingmaterials/activities#4]
If people start to use "restarts" a lot, the storage size could become big. e.g., if you have an MD run that requires 20 restarts, you may want to store full outputs only for the last part and abbreviated outputs for the previous restarts.

Is there any way to control database size - particularly when restarting?

**Comment by utf** [comment]
This is possible currently using the `Response` object. The output is only stored if it is specified. Consider the example:

```
@job
def run_md(inputs):
    # run md calculation
    ...
    
    if calculation_finished:
        return calculation_output
    else:
        Response(restart=new_md_job)
```

The output is only stored for the final calculation.

Alternatively, if the job were written as:

```
@job
def run_md(inputs):
    # run md calculation
    ...
    
    if calculation_finished:
        return calculation_output
    else:
        Response(output=calculation_output, restart=new_md_job)
```

Then the output would be stored for every job.

**Comment by computron** [comment]
I think this is fine unless otherwise flagged later, closing
