### ISSUE TITLE
Rename package?

### ISSUE THREAD

**Issue by utf** [hackingmaterials/activities#8]
Activities is a bit of a wordy name. Here are some other options (of dubious quality).

- jobble
- joba
- jobster
- workup
- workmate
- enact
- acta

Any thoughts? @computron @davidwaroquiers @gpetretto @gmrigna

**Comment by gmrigna** [comment]
Here is a few more (also of dubious quality):

- perfact (perform activities or actions)
- peracta (inspired from your last one, the latin meaning of "peragere" is "to carry through to the end, to complete")
- actrol (activity/action controller)
- flopus (opus = work, fl -> flow) or fluxopus
- fluxis

**Comment by computron** [comment]
I think I prefer "activities" to invented words, it may be hard for users to remember some of these.

The only addition I could contribute is JobFlow, which would make it clear that it is something like a workflow of jobs.

For example, to a new user, it may not be clear whether a Job is the higher-level entity (Jobs are multiple Activities) or an Activity is the higher-level entity (Activities are multiple Jobs). But JobFlow might make it clearer?

**Comment by davidwaroquiers** [comment]
I prefer JobFlow, that makes it quite clear. I don't have other ideas in mind at this stage.

**Comment by gmrigna** [comment]
I think that indeed JobFlow makes things clearer (see e.g. the slide entitled "Central concepts in activities" in Alex's presentation)

**Comment by utf** [comment]
I like `JobFlow`. Or even just `Flow` for the higher level container. The connection to workflow has some connotation that a Flow is more than a static job.

The package itself could be called "flows", this is available on PyPi.

**Comment by computron** [comment]
"Flow" sounds more hip than JobFlow. JobFlow is probably a bit clearer / more explicit but sounds stale. So depends what you are going for. Note that you can also hybridize, e.g. use JobFlow for the object and "flows" for the package name. Anyway I think I am OK with any of these.

**Comment by utf** [comment]
Ok, thank you all for the suggestions. I agree about the pro's and con's of JobFlow. As a hip guy I will rename the package to "flows" and the `Activity` object to `Flow`.

**Comment by utf** [comment]
Oh dear. `flows` is actually taken on pypi. I will use jobflow instead.
